//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Windows;
using System.Windows.Media;
using System.Windows.Media.Effects;
using System.Windows.Media.Media3D;


namespace ShaderPan
{
	
	
	/// <summary>An effect that applies cartoon-like shading (posterization).</summary>
	public class ToonShaderEffect : ShaderEffect
	{
		
		public static readonly DependencyProperty InputProperty = ShaderEffect.RegisterPixelShaderSamplerProperty("Input", typeof(ToonShaderEffect), 0);
		
		public static readonly DependencyProperty LevelsProperty = DependencyProperty.Register("Levels", typeof(double), typeof(ToonShaderEffect), new UIPropertyMetadata(((double)(5D)), PixelShaderConstantCallback(0)));
		
		public ToonShaderEffect()
		{
			PixelShader pixelShader = new PixelShader();
			pixelShader.UriSource = new Uri("C:\\Users\\wenyunchun\\Desktop\\WpfTPL\\shader\\ToonShader.ps", UriKind.Absolute);
			this.PixelShader = pixelShader;

			this.UpdateShaderValue(InputProperty);
			this.UpdateShaderValue(LevelsProperty);
		}
		
		public Brush Input
		{
			get
			{
				return ((Brush)(this.GetValue(InputProperty)));
			}
			set
			{
				this.SetValue(InputProperty, value);
			}
		}
		
		/// <summary>The number of color levels to use.</summary>
		public double Levels
		{
			get
			{
				return ((double)(this.GetValue(LevelsProperty)));
			}
			set
			{
				this.SetValue(LevelsProperty, value);
			}
		}
	}
}
